# Generated by Django 3.1.6 on 2021-08-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210823_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='winner',
            field=models.CharField(default='TBD', max_length=300),
        ),
    ]
