# Generated by Django 3.1.6 on 2021-08-25 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionlisting_winner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingcomment',
            old_name='comments',
            new_name='comment',
        ),
    ]
