# Generated by Django 3.1.6 on 2021-08-28 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210825_1805'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
